### ISSUE TITLE
multibit won't start

### ISSUE THREAD

**Issue by gcberger** [keepkey/multibit-hd#919]
Multibit 0.3.0 fails to run on my Ubuntu 14.04 machine.  If I double-click its desktop icon nothing happens.  If I try to run from the command line I get an error dump.  The dump text is shown below.

I've used various versions Multibit-HD on this machine successfully in the past, but it's been a while.  I just installed 0.3.0, which produced the error below.  Older versions seem to have the same problem now.

Any ideas?  Please let me know if you need more information.

George

```
agnes:george> ./multibit-hd &
[1] 10603
10:03:01 ~/programs/multibit-hd-unix-0.3.0
agnes:george> [Fatal Error] i4jupd3107466427938365317.xml:1:1: Premature end of file.
In action "Update descriptor entry [Set a variable]" (screen "Startup"), property "Script":
java.lang.NullPointerException
        at com.install4j.script.I4jScript_Internal_59.eval(I4jScript_Internal_59.java:1)
        at com.install4j.script.I4jScript_Internal_59.evaluate(I4jScript_Internal_59.java:*25)
        at com.install4j.runtime.installer.helper.Script.evaluate(Script.java:29)
        at com.install4j.runtime.installer.ContextImpl.runScript(ContextImpl.java:181)
        at com.install4j.runtime.installer.ContextImpl.runScript(ContextImpl.java:176)
        at com.install4j.runtime.beans.actions.control.SetVariableAction.execute(SetVariableAction.java:64)
        at com.install4j.runtime.beans.actions.SystemInstallOrUninstallAction.install(SystemInstallOrUninstallAction.java:23)
        at com.install4j.runtime.installer.InstallerContextImpl$2.fetchValue(InstallerContextImpl.java:170)
        at com.install4j.runtime.installer.InstallerContextImpl$2.fetchValue(InstallerContextImpl.java:167)
        at com.install4j.runtime.installer.helper.comm.actions.FetchObjectAction.execute(FetchObjectAction.java:14)
        at com.install4j.runtime.installer.helper.comm.HelperCommunication.executeActionDirect(HelperCommunication.java:266)
        at com.install4j.runtime.installer.helper.comm.HelperCommunication.executeActionInt(HelperCommunication.java:241)
        at com.install4j.runtime.installer.helper.comm.HelperCommunication.executeActionChecked(HelperCommunication.java:179)
        at com.install4j.runtime.installer.helper.comm.HelperCommunication.fetchObjectChecked(HelperCommunication.java:162)
        at com.install4j.runtime.installer.InstallerContextImpl.performActionIntStatic(InstallerContextImpl.java:167)
        at com.install4j.runtime.installer.InstallerContextImpl.performActionInt(InstallerContextImpl.java:155)
        at com.install4j.runtime.installer.ContextImpl.performAction(ContextImpl.java:1058)
        at com.install4j.runtime.installer.controller.Controller.executeActions(Controller.java:318)
        at com.install4j.runtime.installer.controller.Controller.handleCommand(Controller.java:170)
        at com.install4j.runtime.installer.controller.Controller.handleStartup(Controller.java:113)
        at com.install4j.runtime.installer.controller.Controller.start(Controller.java:70)
        at com.install4j.runtime.installer.Application.runApplication(Application.java:75)
        at com.install4j.runtime.installer.Application.runApplicationInProcess(Application.java:53)
        at com.install4j.runtime.installer.helper.apiimpl.ApplicationLauncherImpl$1.run(ApplicationLauncherImpl.java:39)
        at com.install4j.runtime.installer.helper.apiimpl.ApplicationLauncherImpl.launchApplicationInProcess(ApplicationLauncherImpl.java:46)
        at com.install4j.api.launcher.ApplicationLauncher.launchApplicationInProcess(ApplicationLauncher.java:58)
        at com.install4j.runtime.launcher.LauncherIntegration$2.run(LauncherIntegration.java:117)
        at com.install4j.runtime.launcher.LauncherIntegration.processLauncherIntegration(LauncherIntegration.java:121)
        at com.install4j.runtime.launcher.LauncherIntegration.processLauncherIntegrations(LauncherIntegration.java:65)
        at com.install4j.runtime.launcher.LauncherIntegration.processLauncherIntegrations(LauncherIntegration.java:58)
        at com.install4j.runtime.launcher.LauncherIntegration.checkIntegrations(LauncherIntegration.java:45)
        at com.install4j.runtime.launcher.Launcher.init(Launcher.java:106)
        at com.install4j.runtime.launcher.UnixLauncher.main(UnixLauncher.java:23)
[2016-08-23 10:03:02,927] DEBUG [main] o.m.h.c.m.InstallationManager - Application data directory is
'/home/george/.MultiBitHD' 
[2016-08-23 10:03:03,025] INFO  [main] o.m.h.c.l.LoggingFactory - LoggingFactory bootstrap completed. 
[2016-08-23 10:03:03,088] INFO  [main] o.m.h.c.s.AbstractService - Service ConfigurationService@7592b321 starting... 
[2016-08-23 10:03:03,089] DEBUG [main] o.m.h.c.s.CoreServices - Loading configuration... 
[2016-08-23 10:03:03,089] WARN  [main] o.m.h.c.s.CoreServices - Using default configuration 
[2016-08-23 10:03:03,211] DEBUG [main] o.m.h.c.s.CoreServices - Context identity: 969463236 
[2016-08-23 10:03:03,212] INFO  [main] o.m.h.u.MultiBitHD - No command line arguments 
[2016-08-23 10:03:03,214] DEBUG [main] o.m.h.u.s.ExternalDataListeningService - No command line arguments to parse 
[2016-08-23 10:03:03,214] INFO  [main] o.m.h.c.s.AbstractService - Service ExternalDataListeningService@2fcb94 starting... 
[2016-08-23 10:03:03,215] DEBUG [main] o.m.c.c.SafeExecutors - New fixed thread pool with 1 threads: 'uri-listener' 
[2016-08-23 10:03:03,220] INFO  [main] o.m.h.u.s.ExternalDataListeningService - Listening for MultiBit HD instances on socket: '8330' 
[2016-08-23 10:03:03,220] INFO  [main] o.m.h.u.MultiBitHD - This is the primary instance so showing splash screen. 
[2016-08-23 10:03:03,225] ERROR [AWT-EventQueue-0] o.m.h.c.e.ExceptionHandler - Uncaught exception. Proceeding to show Error Reporting dialog... ! java.awt.HeadlessException: null
! at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:207) ~[na:1.7.0_111]
! at java.awt.Window.<init>(Window.java:535) ~[na:1.7.0_111]
! at java.awt.Frame.<init>(Frame.java:420) ~[na:1.7.0_111]
! at java.awt.Frame.<init>(Frame.java:385) ~[na:1.7.0_111]
! at javax.swing.JFrame.<init>(JFrame.java:174) ~[na:1.7.0_111]
! at com.exe4j.runtime.util.InternalErrorFrame.<init>(InternalErrorFrame.java:24) ~[i4jruntime.jar:na]
! at com.exe4j.runtime.LauncherEngine$1.run(LauncherEngine.java:112) ~[i4jruntime.jar:na]
! at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312) ~[na:1.7.0_111]
! at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:745) ~[na:1.7.0_111]
! at java.awt.EventQueue.access$300(EventQueue.java:103) ~[na:1.7.0_111]
! at java.awt.EventQueue$3.run(EventQueue.java:706) ~[na:1.7.0_111]
! at java.awt.EventQueue$3.run(EventQueue.java:704) ~[na:1.7.0_111]
! at java.security.AccessController.doPrivileged(Native Method) ~[na:1.7.0_111]
! at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76) ~[na:1.7.0_111]
! at java.awt.EventQueue.dispatchEvent(EventQueue.java:715) ~[na:1.7.0_111]
! at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242) [na:1.7.0_111]
! at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161) [na:1.7.0_111]
! at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150) [na:1.7.0_111]
! at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146) [na:1.7.0_111]
! at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138) [na:1.7.0_111]
! at java.awt.EventDispatchThread.run(EventDispatchThread.java:91) [na:1.7.0_111]

[2016-08-23 10:03:03,228] ERROR [AWT-EventQueue-0] o.m.h.c.e.ExceptionHandler - Unable to use standard error reporting dialog. ! java.lang.reflect.InvocationTargetException: null
! at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.7.0_111]
! at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) ~[na:1.7.0_111]
! at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.7.0_111]
! at java.lang.reflect.Constructor.newInstance(Constructor.java:526) ~[na:1.7.0_111]
! at org.multibit.hd.core.error_reporting.ExceptionHandler$1.run(ExceptionHandler.java:105) ~[multibit-hd.jar:na]
! at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312) [na:1.7.0_111]
! at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:745) [na:1.7.0_111]
! at java.awt.EventQueue.access$300(EventQueue.java:103) [na:1.7.0_111]
! at java.awt.EventQueue$3.run(EventQueue.java:706) [na:1.7.0_111]
! at java.awt.EventQueue$3.run(EventQueue.java:704) [na:1.7.0_111]
! at java.security.AccessController.doPrivileged(Native Method) [na:1.7.0_111]
! at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76) [na:1.7.0_111]
! at java.awt.EventQueue.dispatchEvent(EventQueue.java:715) [na:1.7.0_111]
! at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242) [na:1.7.0_111]
! at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161) [na:1.7.0_111]
! at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150) [na:1.7.0_111]
! at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146) [na:1.7.0_111]
! at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138) [na:1.7.0_111]
! at java.awt.EventDispatchThread.run(EventDispatchThread.java:91) [na:1.7.0_111]
Caused by: ! java.awt.HeadlessException: null
! at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:207) ~[na:1.7.0_111]
! at java.awt.Window.<init>(Window.java:535) ~[na:1.7.0_111]
! at java.awt.Frame.<init>(Frame.java:420) ~[na:1.7.0_111]
! at java.awt.Frame.<init>(Frame.java:385) ~[na:1.7.0_111]
! at javax.swing.JFrame.<init>(JFrame.java:174) ~[na:1.7.0_111]
! at org.multibit.hd.ui.error_reporting.ErrorReportingDialog.<init>(ErrorReportingDialog.java:78) ~[multibit-hd.jar:na]
!... 19 common frames omitted

[2016-08-23 10:03:03,239] ERROR [AWT-EventQueue-0] o.m.h.c.e.ExceptionHandler - Unable to use fallback error reporting dialog. Forcing immediate shutdown. ! java.awt.HeadlessException: null
! at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:207) ~[na:1.7.0_111]
! at java.awt.Window.<init>(Window.java:535) ~[na:1.7.0_111]
! at java.awt.Frame.<init>(Frame.java:420) ~[na:1.7.0_111]
! at java.awt.Frame.<init>(Frame.java:385) ~[na:1.7.0_111]
! at javax.swing.SwingUtilities$SharedOwnerFrame.<init>(SwingUtilities.java:1756) ~[na:1.7.0_111]
! at javax.swing.SwingUtilities.getSharedOwnerFrame(SwingUtilities.java:1831) ~[na:1.7.0_111]
! at javax.swing.JOptionPane.getRootFrame(JOptionPane.java:1697) ~[na:1.7.0_111]
! at javax.swing.JOptionPane.showOptionDialog(JOptionPane.java:863) ~[na:1.7.0_111]
! at javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:667) ~[na:1.7.0_111]
! at javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:638) ~[na:1.7.0_111]
! at org.multibit.hd.core.error_reporting.ExceptionHandler$1.run(ExceptionHandler.java:112) ~[multibit-hd.jar:na]
! at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312) [na:1.7.0_111]
! at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:745) [na:1.7.0_111]
! at java.awt.EventQueue.access$300(EventQueue.java:103) [na:1.7.0_111]
! at java.awt.EventQueue$3.run(EventQueue.java:706) [na:1.7.0_111]
! at java.awt.EventQueue$3.run(EventQueue.java:704) [na:1.7.0_111]
! at java.security.AccessController.doPrivileged(Native Method) [na:1.7.0_111]
! at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76) [na:1.7.0_111]
! at java.awt.EventQueue.dispatchEvent(EventQueue.java:715) [na:1.7.0_111]
! at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242) [na:1.7.0_111]
! at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161) [na:1.7.0_111]
! at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150) [na:1.7.0_111]
! at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146) [na:1.7.0_111]
! at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138) [na:1.7.0_111]
! at java.awt.EventDispatchThread.run(EventDispatchThread.java:91) [na:1.7.0_111]


[1]+  Exit 255                ./multibit-hd
```

**Comment by kliyer** [comment]
Hi George sorry to hear MultiBit is not starting on ubuntu for you. I would suggest you contact the KeepKey Support Desk at https://keepkey.freshdesk.com/support/solutions.
